//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKHomeProj.ApkShellExt.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KKHomeProj.ApkShellExt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] adb {
            get {
                object obj = ResourceManager.GetObject("adb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap deficon {
            get {
                object obj = ResourceManager.GetObject("deficon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 No device attached! 的本地化字符串。
        /// </summary>
        internal static string menu_CannotFindPhone {
            get {
                return ResourceManager.GetString("menu_CannotFindPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect adb with TCP/IP via WIFI 的本地化字符串。
        /// </summary>
        internal static string menu_comment_ConnectViaWIFI {
            get {
                return ResourceManager.GetString("menu_comment_ConnectViaWIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install to your device via adb 的本地化字符串。
        /// </summary>
        internal static string menu_comment_InstallToPhone {
            get {
                return ResourceManager.GetString("menu_comment_InstallToPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect device via WIFI 的本地化字符串。
        /// </summary>
        internal static string menu_ConnectViaWIFI {
            get {
                return ResourceManager.GetString("menu_ConnectViaWIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        internal static string menu_DisconnectWIFI {
            get {
                return ResourceManager.GetString("menu_DisconnectWIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To Memory 的本地化字符串。
        /// </summary>
        internal static string menu_InstallToInternalMemory {
            get {
                return ResourceManager.GetString("menu_InstallToInternalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install to Device 的本地化字符串。
        /// </summary>
        internal static string menu_InstallToPhone {
            get {
                return ResourceManager.GetString("menu_InstallToPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To SD card 的本地化字符串。
        /// </summary>
        internal static string menu_InstallToSDCard {
            get {
                return ResourceManager.GetString("menu_InstallToSDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall 的本地化字符串。
        /// </summary>
        internal static string menu_Uninstall {
            get {
                return ResourceManager.GetString("menu_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot connect this IP. 的本地化字符串。
        /// </summary>
        internal static string prompt_ConnectFail {
            get {
                return ResourceManager.GetString("prompt_ConnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the IP and port number of your device: 的本地化字符串。
        /// </summary>
        internal static string prompt_ConnectViaWIFI {
            get {
                return ResourceManager.GetString("prompt_ConnectViaWIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please type the IP of your device, like 192.168.0.11:5555 的本地化字符串。
        /// </summary>
        internal static string prompt_NotAnIP {
            get {
                return ResourceManager.GetString("prompt_NotAnIP", resourceCulture);
            }
        }
    }
}
