//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApkShellext2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NonLocalizeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NonLocalizeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApkShellext2.Properties.NonLocalizeResources", typeof(NonLocalizeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taskkill /f /im explorer.exe &amp; cd /d %USERPROFILE%\AppData\Local\Microsoft\Windows\Explorer &amp; attrib -h *.db &amp; del thumbcache_*.db iconcache_*.db &amp; start explorer.exe.
        /// </summary>
        internal static string cmdClearCache {
            get {
                return ResourceManager.GetString("cmdClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconAmazonStore {
            get {
                object obj = ResourceManager.GetObject("iconAmazonStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconAndroid {
            get {
                object obj = ResourceManager.GetObject("iconAndroid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconApkMirror {
            get {
                object obj = ResourceManager.GetObject("iconApkMirror", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconApple {
            get {
                object obj = ResourceManager.GetObject("iconApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconAppStore {
            get {
                object obj = ResourceManager.GetObject("iconAppStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconGitHub {
            get {
                object obj = ResourceManager.GetObject("iconGitHub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconGooglePlay {
            get {
                object obj = ResourceManager.GetObject("iconGooglePlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconMSStore {
            get {
                object obj = ResourceManager.GetObject("iconMSStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconRename {
            get {
                object obj = ResourceManager.GetObject("iconRename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconUpdate {
            get {
                object obj = ResourceManager.GetObject("iconUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output {
            get {
                object obj = ResourceManager.GetObject("output", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Patreon {
            get {
                object obj = ResourceManager.GetObject("Patreon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QR_Scan {
            get {
                object obj = ResourceManager.GetObject("QR_Scan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %AppName%
        ///%Package%
        ///Version: %Version% %Revision%.
        /// </summary>
        internal static string strInfoTipDefault {
            get {
                return ResourceManager.GetString("strInfoTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %AppName%_%Version%.
        /// </summary>
        internal static string strRenamePatternDefault {
            get {
                return ResourceManager.GetString("strRenamePatternDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Stores.
        /// </summary>
        internal static string strSearchStore {
            get {
                return ResourceManager.GetString("strSearchStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/s?k={0}&amp;i=mobile-apps.
        /// </summary>
        internal static string urlAmazonAppStore {
            get {
                return ResourceManager.GetString("urlAmazonAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.apkmirror.com/?s={0}&amp;searchtype=apk.
        /// </summary>
        internal static string urlApkMirror {
            get {
                return ResourceManager.GetString("urlApkMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://itunes.apple.com/app/id{0}.
        /// </summary>
        internal static string urlAppleStore {
            get {
                return ResourceManager.GetString("urlAppleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kkguo.github.io/apkshellext.
        /// </summary>
        internal static string urlGithubHome {
            get {
                return ResourceManager.GetString("urlGithubHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kkguo.github.io/apkshellext/latest.
        /// </summary>
        internal static string urlGithubHomeLatest {
            get {
                return ResourceManager.GetString("urlGithubHomeLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kkguo.github.io/apkshellext/index.html?version={0}.
        /// </summary>
        internal static string urlGithubHomeWithVersion {
            get {
                return ResourceManager.GetString("urlGithubHomeWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://play.google.com/store/search?q={0}&amp;c=apps.
        /// </summary>
        internal static string urlGooglePlay {
            get {
                return ResourceManager.GetString("urlGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.windowsphone.com/s?appid={0}.
        /// </summary>
        internal static string urlMicrosoftStore {
            get {
                return ResourceManager.GetString("urlMicrosoftStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.patreon.com/apkshellext.
        /// </summary>
        internal static string urlPatreon {
            get {
                return ResourceManager.GetString("urlPatreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/kkguo/apkshellext/wiki/Package-information-Pattern-variables.
        /// </summary>
        internal static string urlPatternVarWiki {
            get {
                return ResourceManager.GetString("urlPatternVarWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://crowdin.com/project/apkshellext.
        /// </summary>
        internal static string urlTranslate {
            get {
                return ResourceManager.GetString("urlTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID.
        /// </summary>
        internal static string varAppid {
            get {
                return ResourceManager.GetString("varAppid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppName.
        /// </summary>
        internal static string varAppName {
            get {
                return ResourceManager.GetString("varAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attr\((.*),(.*)\).
        /// </summary>
        internal static string varAttribute {
            get {
                return ResourceManager.GetString("varAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuggable.
        /// </summary>
        internal static string varDebuggable {
            get {
                return ResourceManager.GetString("varDebuggable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSize.
        /// </summary>
        internal static string varFileSize {
            get {
                return ResourceManager.GetString("varFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModify.
        /// </summary>
        internal static string varLastModify {
            get {
                return ResourceManager.GetString("varLastModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS.
        /// </summary>
        internal static string varOS {
            get {
                return ResourceManager.GetString("varOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string varPackage {
            get {
                return ResourceManager.GetString("varPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string varPublisher {
            get {
                return ResourceManager.GetString("varPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        internal static string varRevision {
            get {
                return ResourceManager.GetString("varRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string varVersion {
            get {
                return ResourceManager.GetString("varVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows {
            get {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
