//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApkShellext2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApkShellext2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Page on GitHub.
        /// </summary>
        internal static string btnGitHub {
            get {
                return ResourceManager.GetString("btnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Last Saved Pattern.
        /// </summary>
        internal static string btnResetPattern {
            get {
                return ResourceManager.GetString("btnResetPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearchAdb {
            get {
                return ResourceManager.GetString("btnSearchAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the project site for update.
        /// </summary>
        internal static string btnUpdateToolTip {
            get {
                return ResourceManager.GetString("btnUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All open File Explorer will be closed, Continue?.
        /// </summary>
        internal static string dialogClearCache {
            get {
                return ResourceManager.GetString("dialogClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to display icon and thumbnail correctly, the cache need to be cleared, clear it now?.
        /// </summary>
        internal static string dialogNeedClearCache {
            get {
                return ResourceManager.GetString("dialogNeedClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenamePattern.
        /// </summary>
        internal static string lblRenamePattern {
            get {
                return ResourceManager.GetString("lblRenamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0} in Amazon Appstore.
        /// </summary>
        internal static string menuGotoAmazonAppStore {
            get {
                return ResourceManager.GetString("menuGotoAmazonAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0} in ApkMirror.com.
        /// </summary>
        internal static string menuGotoApkMirror {
            get {
                return ResourceManager.GetString("menuGotoApkMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0} in Apple Appstore.
        /// </summary>
        internal static string menuGotoAppleAppStore {
            get {
                return ResourceManager.GetString("menuGotoAppleAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0} in GooglePlay.
        /// </summary>
        internal static string menuGotoGooglePlay {
            get {
                return ResourceManager.GetString("menuGotoGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0} in Microsoft Store.
        /// </summary>
        internal static string menuGotoMicrosoftStore {
            get {
                return ResourceManager.GetString("menuGotoMicrosoftStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK Shell Extension.
        /// </summary>
        internal static string menuMain {
            get {
                return ResourceManager.GetString("menuMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string menuPreferences {
            get {
                return ResourceManager.GetString("menuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename to {0}.
        /// </summary>
        internal static string menuRenameAs {
            get {
                return ResourceManager.GetString("menuRenameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify path of adb.exe.
        /// </summary>
        internal static string strAdbPath {
            get {
                return ResourceManager.GetString("strAdbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show app store menus when selected multiple files.
        /// </summary>
        internal static string strAlwaysShowGooglePlay {
            get {
                return ResourceManager.GetString("strAlwaysShowGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, app store menus will show up even multiple apk files selected. 
        ///Please note, you may open a lot of browser window and impact the performance significantly.
        ///By default, only show the menu when one file selected.
        /// </summary>
        internal static string strAlwaysShowGooglePlayToolTip {
            get {
                return ResourceManager.GetString("strAlwaysShowGooglePlayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking new version ....
        /// </summary>
        internal static string strCheckingNewVersion {
            get {
                return ResourceManager.GetString("strCheckingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check project site for update..
        /// </summary>
        internal static string strCheckProjectSite {
            get {
                return ResourceManager.GetString("strCheckProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Icon and Thumbnail cache.
        /// </summary>
        internal static string strClearCache {
            get {
                return ResourceManager.GetString("strClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version: {0}.
        /// </summary>
        internal static string strCurrVersion {
            get {
                return ResourceManager.GetString("strCurrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Thumbnail instead of Icon..
        /// </summary>
        internal static string strEnableThumbnail {
            get {
                return ResourceManager.GetString("strEnableThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! You have the latest version..
        /// </summary>
        internal static string strGotLatest {
            get {
                return ResourceManager.GetString("strGotLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to ApkShellext2 Project site.
        /// </summary>
        internal static string strGotoProjectSite {
            get {
                return ResourceManager.GetString("strGotoProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help to translate this project..
        /// </summary>
        internal static string strHelpTranslate {
            get {
                return ResourceManager.GetString("strHelpTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %AppName%
        ///%Package%
        ///Version: %Version% %Revision%.
        /// </summary>
        internal static string strInfoTipDefault {
            get {
                return ResourceManager.GetString("strInfoTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Tip Pattern:.
        /// </summary>
        internal static string strInfoTipPattern {
            get {
                return ResourceManager.GetString("strInfoTipPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Language:.
        /// </summary>
        internal static string strLanguages {
            get {
                return ResourceManager.GetString("strLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires ApkShellextService, please make sure the service started..
        /// </summary>
        internal static string strNeedApkShellextService {
            get {
                return ResourceManager.GetString("strNeedApkShellextService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0} is availible.
        /// </summary>
        internal static string strNewVersionAvailible {
            get {
                return ResourceManager.GetString("strNewVersionAvailible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApkShellext2 Preferences.
        /// </summary>
        internal static string strPreferencesCaption {
            get {
                return ResourceManager.GetString("strPreferencesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to read file.
        /// </summary>
        internal static string strReadFileFailed {
            get {
                return ResourceManager.GetString("strReadFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable usage please refer to Project Wiki.
        /// </summary>
        internal static string strReferToWiki {
            get {
                return ResourceManager.GetString("strReferToWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to rename this file as {0}?.
        /// </summary>
        internal static string strRenameConfirm {
            get {
                return ResourceManager.GetString("strRenameConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Pattern: (without extension).
        /// </summary>
        internal static string strRenamePattern {
            get {
                return ResourceManager.GetString("strRenamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %AppName%_%Version%.
        /// </summary>
        internal static string strRenamePatternDefault {
            get {
                return ResourceManager.GetString("strRenamePatternDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For avoiding situation of same Version but different revision number, this most like happens in android app files. 
        ///By checking this, rename app file as %AppName%_%Version%_%Revision%, otherwise, use %AppName%_%Version%..
        /// </summary>
        internal static string strRenameToolTip {
            get {
                return ResourceManager.GetString("strRenameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Space with _.
        /// </summary>
        internal static string strReplaceSpaceWith_ {
            get {
                return ResourceManager.GetString("strReplaceSpaceWith_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code to download.
        /// </summary>
        internal static string strScanToDownload {
            get {
                return ResourceManager.GetString("strScanToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Stores.
        /// </summary>
        internal static string strSearchStore {
            get {
                return ResourceManager.GetString("strSearchStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu to Amazon App Store.
        /// </summary>
        internal static string strShowAmazonStore {
            get {
                return ResourceManager.GetString("strShowAmazonStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu to ApkMirror.
        /// </summary>
        internal static string strShowApkMirror {
            get {
                return ResourceManager.GetString("strShowApkMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu to Apple App Store (for ipa).
        /// </summary>
        internal static string strShowAppleStore {
            get {
                return ResourceManager.GetString("strShowAppleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display WindowsPhone app (appx, appxbundle) icon..
        /// </summary>
        internal static string strShowAppxIcon {
            get {
                return ResourceManager.GetString("strShowAppxIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display icon for context menu.
        /// </summary>
        internal static string strShowContextMenuIcon {
            get {
                return ResourceManager.GetString("strShowContextMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu to Google play.
        /// </summary>
        internal static string strShowGooglePlay {
            get {
                return ResourceManager.GetString("strShowGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display iOS app (ipa) icon..
        /// </summary>
        internal static string strShowIpaIcon {
            get {
                return ResourceManager.GetString("strShowIpaIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu to Microsoft Store (for appx/appxbundle).
        /// </summary>
        internal static string strShowMSStore {
            get {
                return ResourceManager.GetString("strShowMSStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice me when new version is availible.
        /// </summary>
        internal static string strShowNewVerInfo {
            get {
                return ResourceManager.GetString("strShowNewVerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Overlay Icon for different OS.
        /// </summary>
        internal static string strShowOverlayIcon {
            get {
                return ResourceManager.GetString("strShowOverlayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display overlay icon for different OS.
        /// </summary>
        internal static string strShowOverlayIconToolTip {
            get {
                return ResourceManager.GetString("strShowOverlayIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch thumbnail if Windows requesting larger size.
        /// </summary>
        internal static string strStretchThumbnail {
            get {
                return ResourceManager.GetString("strStretchThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        internal static string twContextMenu {
            get {
                return ResourceManager.GetString("twContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string twGeneral {
            get {
                return ResourceManager.GetString("twGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string twIcon {
            get {
                return ResourceManager.GetString("twIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoTip.
        /// </summary>
        internal static string twInfotip {
            get {
                return ResourceManager.GetString("twInfotip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming.
        /// </summary>
        internal static string twRename {
            get {
                return ResourceManager.GetString("twRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string twThumbnail {
            get {
                return ResourceManager.GetString("twThumbnail", resourceCulture);
            }
        }
    }
}
