//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApkShellext2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApkShellext2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Official Page on GitHub 的本地化字符串。
        /// </summary>
        internal static string btnGitHub {
            get {
                return ResourceManager.GetString("btnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Last Saved Pattern 的本地化字符串。
        /// </summary>
        internal static string btnResetPattern {
            get {
                return ResourceManager.GetString("btnResetPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string btnSearchAdb {
            get {
                return ResourceManager.GetString("btnSearchAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check the project site for update 的本地化字符串。
        /// </summary>
        internal static string btnUpdateToolTip {
            get {
                return ResourceManager.GetString("btnUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 taskkill /f /im explorer.exe &amp; cd /d %USERPROFILE%\AppData\Local\Microsoft\Windows\Explorer &amp; attrib -h *.db &amp; del thumbcache_*.db iconcache_*.db &amp; start explorer.exe 的本地化字符串。
        /// </summary>
        internal static string cmdClearCache {
            get {
                return ResourceManager.GetString("cmdClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All open File Explorer will be closed, Continue? 的本地化字符串。
        /// </summary>
        internal static string dialogClearCache {
            get {
                return ResourceManager.GetString("dialogClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In order to display icon and thumbnail correctly, the cache need to be cleared, clear it now? 的本地化字符串。
        /// </summary>
        internal static string dialogNeedClearCache {
            get {
                return ResourceManager.GetString("dialogNeedClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconAmazonStore {
            get {
                object obj = ResourceManager.GetObject("iconAmazonStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconAndroid {
            get {
                object obj = ResourceManager.GetObject("iconAndroid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconApkMirror {
            get {
                object obj = ResourceManager.GetObject("iconApkMirror", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconApple {
            get {
                object obj = ResourceManager.GetObject("iconApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconAppStore {
            get {
                object obj = ResourceManager.GetObject("iconAppStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconGitHub {
            get {
                object obj = ResourceManager.GetObject("iconGitHub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconGooglePlay {
            get {
                object obj = ResourceManager.GetObject("iconGooglePlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconMSStore {
            get {
                object obj = ResourceManager.GetObject("iconMSStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconRename {
            get {
                object obj = ResourceManager.GetObject("iconRename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconUpdate {
            get {
                object obj = ResourceManager.GetObject("iconUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 RenamePattern 的本地化字符串。
        /// </summary>
        internal static string lblRenamePattern {
            get {
                return ResourceManager.GetString("lblRenamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Check {0} on Amazon Appstore 的本地化字符串。
        /// </summary>
        internal static string menuGotoAmazonAppStore {
            get {
                return ResourceManager.GetString("menuGotoAmazonAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check {0} on ApkMirror.com 的本地化字符串。
        /// </summary>
        internal static string menuGotoApkMirror {
            get {
                return ResourceManager.GetString("menuGotoApkMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check {0} on Apple Appstore 的本地化字符串。
        /// </summary>
        internal static string menuGotoAppleAppStore {
            get {
                return ResourceManager.GetString("menuGotoAppleAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check {0} on GooglePlay 的本地化字符串。
        /// </summary>
        internal static string menuGotoGooglePlay {
            get {
                return ResourceManager.GetString("menuGotoGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check {0} on Microsoft Store 的本地化字符串。
        /// </summary>
        internal static string menuGotoMicrosoftStore {
            get {
                return ResourceManager.GetString("menuGotoMicrosoftStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APK Shell Extension 的本地化字符串。
        /// </summary>
        internal static string menuMain {
            get {
                return ResourceManager.GetString("menuMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferences &amp;&amp; Update 的本地化字符串。
        /// </summary>
        internal static string menuPreferences {
            get {
                return ResourceManager.GetString("menuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename to {0} 的本地化字符串。
        /// </summary>
        internal static string menuRenameAs {
            get {
                return ResourceManager.GetString("menuRenameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap QR_Scan {
            get {
                object obj = ResourceManager.GetObject("QR_Scan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify path of adb.exe 的本地化字符串。
        /// </summary>
        internal static string strAdbPath {
            get {
                return ResourceManager.GetString("strAdbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show app store menus when selected multiple files 的本地化字符串。
        /// </summary>
        internal static string strAlwaysShowGooglePlay {
            get {
                return ResourceManager.GetString("strAlwaysShowGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If checked, app store menus will show up even multiple apk files selected. 
        ///Please note, you may open a lot of browser window and impact the performance significantly.
        ///By default, only show the menu when one file selected 的本地化字符串。
        /// </summary>
        internal static string strAlwaysShowGooglePlayToolTip {
            get {
                return ResourceManager.GetString("strAlwaysShowGooglePlayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking new version ... 的本地化字符串。
        /// </summary>
        internal static string strCheckingNewVersion {
            get {
                return ResourceManager.GetString("strCheckingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check project site for update. 的本地化字符串。
        /// </summary>
        internal static string strCheckProjectSite {
            get {
                return ResourceManager.GetString("strCheckProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Icon and Thumbnail cache 的本地化字符串。
        /// </summary>
        internal static string strClearCache {
            get {
                return ResourceManager.GetString("strClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version: {0} 的本地化字符串。
        /// </summary>
        internal static string strCurrVersion {
            get {
                return ResourceManager.GetString("strCurrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Thumbnail instead of Icon. 的本地化字符串。
        /// </summary>
        internal static string strEnableThumbnail {
            get {
                return ResourceManager.GetString("strEnableThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Great! You have the latest version. 的本地化字符串。
        /// </summary>
        internal static string strGotLatest {
            get {
                return ResourceManager.GetString("strGotLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to ApkShellext2 Project site 的本地化字符串。
        /// </summary>
        internal static string strGotoProjectSite {
            get {
                return ResourceManager.GetString("strGotoProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help to translate this project. 的本地化字符串。
        /// </summary>
        internal static string strHelpTranslate {
            get {
                return ResourceManager.GetString("strHelpTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %AppName%
        ///%Package%
        ///Version: %Version% %Revision% 的本地化字符串。
        /// </summary>
        internal static string strInfoTipDefault {
            get {
                return ResourceManager.GetString("strInfoTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info Tip Pattern: 的本地化字符串。
        /// </summary>
        internal static string strInfoTipPattern {
            get {
                return ResourceManager.GetString("strInfoTipPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Language: 的本地化字符串。
        /// </summary>
        internal static string strLanguages {
            get {
                return ResourceManager.GetString("strLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature requires ApkShellextService, please make sure the service started. 的本地化字符串。
        /// </summary>
        internal static string strNeedApkShellextService {
            get {
                return ResourceManager.GetString("strNeedApkShellextService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version {0} is availible 的本地化字符串。
        /// </summary>
        internal static string strNewVersionAvailible {
            get {
                return ResourceManager.GetString("strNewVersionAvailible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ApkShellext2 Preferences 的本地化字符串。
        /// </summary>
        internal static string strPreferencesCaption {
            get {
                return ResourceManager.GetString("strPreferencesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to read file 的本地化字符串。
        /// </summary>
        internal static string strReadFileFailed {
            get {
                return ResourceManager.GetString("strReadFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable usage please refer to Project Wiki 的本地化字符串。
        /// </summary>
        internal static string strReferToWiki {
            get {
                return ResourceManager.GetString("strReferToWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm to rename this file as {0}? 的本地化字符串。
        /// </summary>
        internal static string strRenameConfirm {
            get {
                return ResourceManager.GetString("strRenameConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename Pattern: (without extension) 的本地化字符串。
        /// </summary>
        internal static string strRenamePattern {
            get {
                return ResourceManager.GetString("strRenamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %AppName%_%Version% 的本地化字符串。
        /// </summary>
        internal static string strRenamePatternDefault {
            get {
                return ResourceManager.GetString("strRenamePatternDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For avoiding situation of same Version but different revision number, this most like happens in android app files. 
        ///By checking this, rename app file as %AppName%_%Version%_%Revision%, otherwise, use %AppName%_%Version%. 的本地化字符串。
        /// </summary>
        internal static string strRenameToolTip {
            get {
                return ResourceManager.GetString("strRenameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace Space with _ 的本地化字符串。
        /// </summary>
        internal static string strReplaceSpaceWith_ {
            get {
                return ResourceManager.GetString("strReplaceSpaceWith_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan QR code to download 的本地化字符串。
        /// </summary>
        internal static string strScanToDownload {
            get {
                return ResourceManager.GetString("strScanToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show menu to Amazon App Store 的本地化字符串。
        /// </summary>
        internal static string strShowAmazonStore {
            get {
                return ResourceManager.GetString("strShowAmazonStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show menu to ApkMirror 的本地化字符串。
        /// </summary>
        internal static string strShowApkMirror {
            get {
                return ResourceManager.GetString("strShowApkMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show menu to Apple App Store (for ipa) 的本地化字符串。
        /// </summary>
        internal static string strShowAppleStore {
            get {
                return ResourceManager.GetString("strShowAppleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display WindowsPhone app (appx, appxbundle) icon. 的本地化字符串。
        /// </summary>
        internal static string strShowAppxIcon {
            get {
                return ResourceManager.GetString("strShowAppxIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display icon for context menu 的本地化字符串。
        /// </summary>
        internal static string strShowContextMenuIcon {
            get {
                return ResourceManager.GetString("strShowContextMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show menu to Google play 的本地化字符串。
        /// </summary>
        internal static string strShowGooglePlay {
            get {
                return ResourceManager.GetString("strShowGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display iOS app (ipa) icon. 的本地化字符串。
        /// </summary>
        internal static string strShowIpaIcon {
            get {
                return ResourceManager.GetString("strShowIpaIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show menu to Microsoft Store (for appx/appxbundle) 的本地化字符串。
        /// </summary>
        internal static string strShowMSStore {
            get {
                return ResourceManager.GetString("strShowMSStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice me when new version is availible 的本地化字符串。
        /// </summary>
        internal static string strShowNewVerInfo {
            get {
                return ResourceManager.GetString("strShowNewVerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Overlay Icon for different OS 的本地化字符串。
        /// </summary>
        internal static string strShowOverlayIcon {
            get {
                return ResourceManager.GetString("strShowOverlayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display overlay icon for different OS 的本地化字符串。
        /// </summary>
        internal static string strShowOverlayIconToolTip {
            get {
                return ResourceManager.GetString("strShowOverlayIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stretch thumbnail if Windows requesting larger size 的本地化字符串。
        /// </summary>
        internal static string strStretchThumbnail {
            get {
                return ResourceManager.GetString("strStretchThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Context Menu 的本地化字符串。
        /// </summary>
        internal static string twContextMenu {
            get {
                return ResourceManager.GetString("twContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string twGeneral {
            get {
                return ResourceManager.GetString("twGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon 的本地化字符串。
        /// </summary>
        internal static string twIcon {
            get {
                return ResourceManager.GetString("twIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InfoTip 的本地化字符串。
        /// </summary>
        internal static string twInfotip {
            get {
                return ResourceManager.GetString("twInfotip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Renaming 的本地化字符串。
        /// </summary>
        internal static string twRename {
            get {
                return ResourceManager.GetString("twRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thumbnail 的本地化字符串。
        /// </summary>
        internal static string twThumbnail {
            get {
                return ResourceManager.GetString("twThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.amazon.com/gp/mas/dl/android?p={0} 的本地化字符串。
        /// </summary>
        internal static string urlAmazonAppStore {
            get {
                return ResourceManager.GetString("urlAmazonAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.apkmirror.com/apk/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string urlApkMirror {
            get {
                return ResourceManager.GetString("urlApkMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://itunes.apple.com/app/id{0} 的本地化字符串。
        /// </summary>
        internal static string urlAppleStore {
            get {
                return ResourceManager.GetString("urlAppleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kkguo.github.io/apkshellext 的本地化字符串。
        /// </summary>
        internal static string urlGithubHome {
            get {
                return ResourceManager.GetString("urlGithubHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kkguo.github.io/apkshellext/latest 的本地化字符串。
        /// </summary>
        internal static string urlGithubHomeLatest {
            get {
                return ResourceManager.GetString("urlGithubHomeLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kkguo.github.io/apkshellext/index.html?version={0} 的本地化字符串。
        /// </summary>
        internal static string urlGithubHomeWithVersion {
            get {
                return ResourceManager.GetString("urlGithubHomeWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://play.google.com/store/apps/details?id={0} 的本地化字符串。
        /// </summary>
        internal static string urlGooglePlay {
            get {
                return ResourceManager.GetString("urlGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.windowsphone.com/s?appid={0} 的本地化字符串。
        /// </summary>
        internal static string urlMicrosoftStore {
            get {
                return ResourceManager.GetString("urlMicrosoftStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/kkguo/apkshellext/wiki/Package-information-Pattern-variables 的本地化字符串。
        /// </summary>
        internal static string urlPatternVarWiki {
            get {
                return ResourceManager.GetString("urlPatternVarWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://crowdin.com/project/apkshellext 的本地化字符串。
        /// </summary>
        internal static string urlTranslate {
            get {
                return ResourceManager.GetString("urlTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %AppID% 的本地化字符串。
        /// </summary>
        internal static string varAppid {
            get {
                return ResourceManager.GetString("varAppid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %AppName% 的本地化字符串。
        /// </summary>
        internal static string varAppName {
            get {
                return ResourceManager.GetString("varAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Debuggable% 的本地化字符串。
        /// </summary>
        internal static string varDebuggable {
            get {
                return ResourceManager.GetString("varDebuggable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %FileSize% 的本地化字符串。
        /// </summary>
        internal static string varFileSize {
            get {
                return ResourceManager.GetString("varFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %LastModify% 的本地化字符串。
        /// </summary>
        internal static string varLastModify {
            get {
                return ResourceManager.GetString("varLastModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %OS% 的本地化字符串。
        /// </summary>
        internal static string varOS {
            get {
                return ResourceManager.GetString("varOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Package% 的本地化字符串。
        /// </summary>
        internal static string varPackage {
            get {
                return ResourceManager.GetString("varPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Publisher% 的本地化字符串。
        /// </summary>
        internal static string varPublisher {
            get {
                return ResourceManager.GetString("varPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Revision% 的本地化字符串。
        /// </summary>
        internal static string varRevision {
            get {
                return ResourceManager.GetString("varRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Version% 的本地化字符串。
        /// </summary>
        internal static string varVersion {
            get {
                return ResourceManager.GetString("varVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Windows {
            get {
                object obj = ResourceManager.GetObject("Windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
